### ISSUE TITLE
Make the download bar more informative

### ISSUE THREAD

**Issue by JopSchaap** [JopSchaap/trustchain-superapp#4]
The download bar currently does not seems to be showing anything useful. It should instead actually show some useful statistics.

![Screenshot_20240228_113228](https://github.com/JopSchaap/trustchain-superapp/assets/59020232/87baf67d-a860-4016-959f-b0624f12b173)

PS: this has no priority

**Comment by AirWinter** [comment]
The. `updateProgress` method in `AppGossiper.kt` seems to be the method that we need to call to have the progress bar update. From the code it seems that it's called with 0 when it shouldn't be and maybe that's why we don't see the bar changing.
<img width="652" alt="Screenshot 2024-02-28 at 20 31 30" src="https://github.com/JopSchaap/trustchain-superapp/assets/72806037/22928bea-0f41-419a-961d-e25a4c0fcdb0">

**Comment by JopSchaap** [comment]
The following gif comes from the [README](https://github.com/JopSchaap/trustchain-superapp/blob/master/README.md) file and it shows the download bar working. The giff shows it working for torrented files, so my guess is that this should work. However this bar could still be quite more informative when no downloading is happening and when it is what it exactly shows.
![](https://github.com/Tribler/trustchain-superapp/raw/master/doc/freedomOfComputing/download_seeded_apk.gif)
